name: Vienna Website CD

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Environment target'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      draft:
        description: 'Draft deployment'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy to Cloudflare Pages

    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.cloudflare_api_token }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.cloudflare_account_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare
        run: |
          commitHash=$(git rev-parse --short HEAD)
          commitMessage=$(git log -1 --pretty=%B)
          if ${{ inputs.draft }}; then
            commitBranch="$GITHUB_REF_NAME-$commitHash"
          else
            commitBranch="main"
          fi
          npx wrangler pages deploy .svelte-kit/cloudflare --project-name=vienna-website-${{ inputs.target }} --commit-hash=$commitHash --commit-message="$commitMessage" --branch="$commitBranch"
          echo "## :rocket: Deployed Vienna Website [${{ inputs.target }}] on Cloudflare Pages" >> $GITHUB_STEP_SUMMARY
